# fly.toml app configuration file generated for routesapi on 2023-05-10T18:18:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "routesapi"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
